### ISSUE TITLE
cloud selection

### ISSUE THREAD

**Issue by irvnet** [irvnet/job-rec-app#2]
GCP vs AWS
- disappointed offers limited compute 
- may be prudent to consider simply using AWS/Sagemaker... or if GCP/Vertex is a more viable resource, possibly use AWS for infra to provide data to Vertex (depending on which ML engine is better suited for the project)
- need some hands on assessment

**Comment by jamar0813** [comment]
Made a decision to go with GCP

**Comment by jamar0813** [comment]
GCP Will be to cloud of choice for the project.
